[mgr]
border_symbol = "│"
border_style = { fg = "#3b4261" }

[tabs]
active = { fg = "#1e2030", bg = "#82aaff", bold = true }
inactive = { fg = "#828bb8", bg = "#1e2030" }

[mode]
normal_main = { fg = "#1e2030", bg = "#82aaff", bold = true }
select_main = { fg = "#1e2030", bg = "#c3e88d", bold = true }
unset_main = { fg = "#1e2030", bg = "#ffc777", bold = true }

[git]
unstaged = { fg = "#ffc777" }
staged = { fg = "#c3e88d" }
untracked = { fg = "#fca7ea" }
