[mgr]
ratio = [1, 3, 4]
sort_by = "natural"
sort_dir_first = true
linemode = "size"
show_hidden = false
show_symlink = true

[opener]
play = [{ run = 'mpv %s', desc = "mpv", orphan = true, for = "unix" }]

[open]
prepend_rules = [
  { mime = "video/*", use = "play" },
  { mime = "audio/*", use = "play" },
]

[[plugin.prepend_fetchers]]
url = "*"
run = "git"
group = "git"

[[plugin.prepend_fetchers]]
url = "*/"
run = "git"
group = "git"
